spring.application.name=nellmodal

# Configuración de Tesseract OCR
raynen.tessdata-path=C:/Program Files/Tesseract-OCR/tessdata
raynen.language=eng

# Configuración de Raynen (VALORES TEMPORALES)
# Cambia 'raynen.exe-path' por la ruta real de tu ejecutable .exe
# Cambia 'raynen.window-title' por el nombre exacto de la ventana
raynen.exe-path=D:/knitcad/soft/Pattern/pattern/Launcher.exe
raynen.window-title=Knit param
